return {
    -- reading
    { text = "Read in order to live.", author = "Gustave Flaubert" },
    { text = "A reader lives a thousand lives before he dies.", author = "George R.R. Martin" },
    { text = "There is no friend as loyal as a book.", author = "Ernest Hemingway" },
    { text = "Today a reader, tomorrow a leader.", author = "Margaret Fuller" },
    { text = "Books are a uniquely portable magic.", author = "Stephen King" },
    { text = "Reading is to the mind what exercise is to the body.", author = "Joseph Addison" },
    { text = "One glance at a book and you hear the voice of another person.", author = "Carl Sagan" },
    { text = "If you only read the books everyone else is reading, you can only think what everyone else is thinking.", author = "Haruki Murakami" },
    { text = "No entertainment is so cheap as reading.", author = "Mary Wortley Montagu" },
    { text = "To learn to read is to light a fire.", author = "Victor Hugo" },
    { text = "Books are mirrors: you only see in them what you already have inside you.", author = "Carlos Ruiz Zafon" },
    { text = "Reading gives us someplace to go when we have to stay where we are.", author = "Mason Cooley" },
    { text = "So many books, so little time.", author = "Frank Zappa" },
    { text = "Good friends, good books, and a sleepy conscience: this is the ideal life.", author = "Mark Twain" },
    { text = "We accept the love we think we deserve.", author = "Stephen Chbosky" },
    { text = "It is better to be hated for what you are than to be loved for what you are not.", author = "André Gide" },
    { text = "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author = "Lao Tzu" },
    { text = "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author = "John Green" },
    { text = "You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author = "Dr. Seuss" },
    { text = "The opposite of love is not hate, it's indifference.", author = "Elie Wiesel" },
    { text = "You only live once, but if you do it right, once is enough.", author = "Mae West" },
    { text = "In three words I can sum up everything I've learned about life: it goes on.", author = "Robert Frost" },
    { text = "It does not do to dwell on dreams and forget to live.", author = "J.K. Rowling" },
    { text = "Life is what happens to us while we are making other plans.", author = "Allen Saunders" },
    { text = "Everything you can imagine is real.", author = "Pablo Picasso" },
    { text = "Life isn't about finding yourself. Life is about creating yourself.", author = "George Bernard Shaw" },
    { text = "I'm not afraid of death; I just don't want to be there when it happens.", author = "Woody Allen" },
    { text = "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author = "Albert Einstein" },
    { text = "A day without sunshine is like, you know, night.", author = "Steve Martin" },
    { text = "I love deadlines. I love the whooshing noise they make as they go by.", author = "Douglas Adams" },
    { text = "Whenever I feel the need to exercise, I lie down until it goes away.", author = "Paul Terry" },
    { text = "Knowing yourself is the beginning of all wisdom.", author = "Aristotle" },
    { text = "The only true wisdom is in knowing you know nothing.", author = "Socrates" },
    { text = "Science gathers knowledge faster than society gathers wisdom.", author = "Isaac Asimov" },
    { text = "May you live every day of your life.", author = "Jonathan Swift" },
    { text = "Never laugh at live dragons.", author = "J.R.R. Tolkien" },
    { text = "Be the change that you wish to see in the world.", author = "Mahatma Gandhi" },
    { text = "Without music, life would be a mistake.", author = "Friedrich Nietzsche" },
    { text = "A day without laughter is a day wasted.", author = "Nicolas Chamfort" },
    { text = "Man is the only creature who refuses to be what he is.", author = "Albert Camus" },
    { text = "There is nothing either good or bad, but thinking makes it so.", author = "William Shakespeare" },
    { text = "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.", author = "Martin Luther King Jr." },
    { text = "Live as if you were to die tomorrow. Learn as if you were to live forever.", author = "Mahatma Gandhi" },
    { text = "Imperfection is beauty, madness is genius, and it's better to be absolutely ridiculous than absolutely boring.", author = "Marilyn Monroe" },
    { text = "We are all in the gutter, but some of us are looking at the stars.", author = "Oscar Wilde" },
    { text = "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.", author = "Neil Gaiman" },
    { text = "I have not failed. I've just found 10,000 ways that won't work.", author = "Thomas A. Edison" },
    { text = "It's never too late to be what you might have been.", author = "George Eliot" },
    { text = "If you tell the truth, you don't have to remember anything.", author = "Mark Twain" },
    { text = "The reason I talk to myself is because I'm the only one whose answers I accept.", author = "George Carlin" },
    { text = "The truth is rarely pure and never simple.", author = "Oscar Wilde" },
    { text = "Perhaps one did not want to be loved so much as to be understood.", author = "George Orwell" },
    { text = "A lie can travel half way around the world while the truth is putting on its shoes.", author = "Mark Twain" },
    { text = "Facts do not cease to exist because they are ignored.", author = "Aldous Huxley" },
    { text = "Friendship is born at the moment when one man says to another: 'What! You too?'", author = "C.S. Lewis" },
    { text = "What is a friend? A single soul dwelling in two bodies.", author = "Aristotle" },
    { text = "Out beyond ideas of wrongdoing and rightdoing there is a field. I'll meet you there.", author = "Rumi" },
    { text = "Life is an awful, ugly place to not have a best friend.", author = "Sarah Dessen" },
    { text = "For every minute you are angry you lose sixty seconds of happiness.", author = "Ralph Waldo Emerson" },
    { text = "Folks are usually about as happy as they make their minds up to be.", author = "Abraham Lincoln" },
    { text = "Time you enjoy wasting is not wasted time.", author = "Marthe Troly-Curtin" },
    { text = "Happiness in intelligent people is the rarest thing I know.", author = "Ernest Hemingway" },
    { text = "Happiness is when what you think, what you say, and what you do are in harmony.", author = "Mahatma Gandhi" },
    { text = "Count your age by friends, not years. Count your life by smiles, not tears.", author = "John Lennon" },
    { text = "Happiness is not something ready made. It comes from your own actions.", author = "Dalai Lama XIV" },
    { text = "There is no greater agony than bearing an untold story inside you.", author = "Maya Angelou" },
    { text = "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", author = "Toni Morrison" },
    { text = "There is nothing to writing. All you do is sit down at a typewriter and bleed.", author = "Ernest Hemingway" },
    { text = "We write to taste life twice, in the moment and in retrospect.", author = "Anaïs Nin" },
    { text = "Fiction is the truth inside the lie.", author = "Stephen King" },
    { text = "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.", author = "J.K. Rowling" },
    { text = "Success is not final, failure is not fatal: it is the courage to continue that counts.", author = "Winston Churchill" },
    { text = "A ship is safe in harbor, but that's not what ships are for.", author = "John A. Shedd" },
    { text = "Logic will get you from A to Z; imagination will get you everywhere.", author = "Albert Einstein" },
    { text = "We are what we pretend to be, so we must be careful about what we pretend to be.", author = "Kurt Vonnegut Jr." },
    { text = "You must have chaos within you to give birth to a dancing star.", author = "Friedrich Nietzsche" },
    { text = "Art washes away from the soul the dust of everyday life.", author = "Pablo Picasso" },
    { text = "Art enables us to find ourselves and lose ourselves at the same time.", author = "Thomas Merton" },
    { text = "Hold fast to dreams, for if dreams die life is a broken-winged bird that cannot fly.", author = "Langston Hughes" },
    { text = "Life's under no obligation to give us what we expect.", author = "Margaret Mitchell" },
    { text = "I am no bird; and no net ensnares me: I am a free human being with an independent will.", author = "Charlotte Brontë" },
    { text = "Everyone thinks of changing the world, but no one thinks of changing himself.", author = "Leo Tolstoy" },
    { text = "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author = "Rumi" },
    { text = "Not all those who wander are lost.", author = "J.R.R. Tolkien" },
    { text = "Tell me, what is it you plan to do with your one wild and precious life?", author = "Mary Oliver" },
    { text = "I have loved the stars too fondly to be fearful of the night.", author = "Sarah Williams" },
    { text = "Be kind, for everyone you meet is fighting a harder battle.", author = "Plato" },
    { text = "Kindness is the language which the deaf can hear and the blind can see.", author = "Mark Twain" },
    { text = "My religion is very simple. My religion is kindness.", author = "Dalai Lama XIV" },
    { text = "All we have to decide is what to do with the time that is given us.", author = "J.R.R. Tolkien" },
    { text = "It is the time you have wasted for your rose that makes your rose so important.", author = "Antoine de Saint-Exupéry" },
    { text = "The mountains are calling and I must go.", author = "John Muir" },
    -- love
    { text = "You've gotta dance like there's nobody watching, love like you'll never be hurt, sing like there's nobody listening, and live like it's heaven on earth.", author = "William W. Purkey" },
    { text = "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.", author = "Bob Marley" },
    { text = "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", author = "Friedrich Nietzsche" },
    { text = "Have you ever been in love? Horrible isn't it? It makes you so vulnerable.", author = "Neil Gaiman" },
    { text = "I love you without knowing how, or when, or from where.", author = "Pablo Neruda" },
    { text = "I love you as certain dark things are to be loved, in secret, between the shadow and the soul.", author = "Pablo Neruda" },
    -- life
    { text = "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author = "Albert Einstein" },
    { text = "I may not have gone where I intended to go, but I think I have ended up where I needed to be.", author = "Douglas Adams" },
    { text = "Do I contradict myself? Very well then I contradict myself, I am large, I contain multitudes.", author = "Walt Whitman" },
    { text = "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.", author = "Eleanor Roosevelt" },
    { text = "We must be willing to let go of the life we planned so as to have the life that is waiting for us.", author = "Joseph Campbell" },
    { text = "Nothing is so painful to the human mind as a great and sudden change.", author = "Mary Wollstonecraft Shelley" },
    -- humor
    { text = "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.", author = "Groucho Marx" },
    { text = "All you need is love. But a little chocolate now and then doesn't hurt.", author = "Charles M. Schulz" },
    { text = "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.", author = "Groucho Marx" },
    { text = "Women and cats will do as they please, and men and dogs should relax and get used to the idea.", author = "Robert A. Heinlein" },
    { text = "Time flies like an arrow; fruit flies like a banana.", author = "Anthony G. Oettinger" },
    { text = "Go to heaven for the climate, hell for the company.", author = "Benjamin Franklin Wade" },
    { text = "Have you ever noticed how 'What the hell' is always the right decision to make?", author = "Terry Johnson" },
    { text = "I love mankind; it's people I can't stand.", author = "Charles M. Schulz" },
    { text = "I am not young enough to know everything.", author = "Oscar Wilde" },
    { text = "My grandmother started walking five miles a day when she was sixty. She's ninety-seven now, and we don't know where the heck she is.", author = "Ellen DeGeneres" },
    { text = "God created war so that Americans would learn geography.", author = "Mark Twain" },
    -- wisdom
    { text = "Better to remain silent and be thought a fool than to speak and remove all doubt.", author = "Maurice Switzer" },
    { text = "Fall seven times, stand up eight.", author = "Paulo Coelho" },
    { text = "Any fool can be happy. It takes a man with real heart to make beauty out of the stuff that makes us weep.", author = "Clive Barker" },
    { text = "The older I grow, the more I distrust the familiar doctrine that age brings wisdom.", author = "H.L. Mencken" },
    { text = "Rummaging in our souls, we often dig up something that ought to have lain there unnoticed.", author = "Leo Tolstoy" },
    { text = "Inside us there is something that has no name, that something is what we are.", author = "José Saramago" },
    -- philosophy
    { text = "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author = "Anne Frank" },
    { text = "Never doubt that a small group of thoughtful, committed citizens can change the world. Indeed, it is the only thing that ever has.", author = "Margaret Mead" },
    { text = "One, remember to look up at the stars and not down at your feet.", author = "Stephen Hawking" },
    { text = "We have to dare to be ourselves, however frightening or strange that self may prove to be.", author = "May Sarton" },
    { text = "People demand freedom of speech as a compensation for the freedom of thought which they seldom use.", author = "Søren Kierkegaard" },
    { text = "Hell is—other people!", author = "Jean-Paul Sartre" },
    { text = "If you're lonely when you're alone, you're in bad company.", author = "Jean-Paul Sartre" },
    { text = "Reality exists in the human mind, and nowhere else.", author = "George Orwell" },
    { text = "The soul becomes dyed with the colour of its thoughts.", author = "Marcus Aurelius" },
    -- inspirational
    { text = "It takes courage to grow up and become who you really are.", author = "E.E. Cummings" },
    { text = "The future belongs to those who believe in the beauty of their dreams.", author = "Eleanor Roosevelt" },
    { text = "Above all, be the heroine of your life, not the victim.", author = "Nora Ephron" },
    { text = "You cannot swim for new horizons until you have courage to lose sight of the shore.", author = "William Faulkner" },
    { text = "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", author = "Rumi" },
    { text = "Confront the dark parts of yourself, and work to banish them with illumination and forgiveness.", author = "August Wilson" },
    { text = "Everyone has talent. What's rare is the courage to follow it to the dark places where it leads.", author = "Erica Jong" },
    { text = "The most courageous act is still to think for yourself. Aloud.", author = "Coco Chanel" },
    { text = "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author = "Roy T. Bennett" },
    -- truth
    { text = "The truth will set you free, but first it will piss you off.", author = "Joe Klaas" },
    { text = "When I despair, I remember that all through history the way of truth and love have always won.", author = "Mahatma Gandhi" },
    { text = "I believe in everything until it's disproved. So I believe in fairies, the myths, dragons. It all exists, even if it's in your mind.", author = "John Lennon" },
    { text = "The truth will set you free. But not until it is finished with you.", author = "David Foster Wallace" },
    { text = "War is peace. Freedom is slavery. Ignorance is strength.", author = "George Orwell" },
    -- friendship
    { text = "Don't walk in front of me; I may not follow. Don't walk behind me; I may not lead. Walk beside me and just be my friend.", author = "Albert Camus" },
    { text = "There is nothing I would not do for those who are really my friends.", author = "Jane Austen" },
    { text = "There is nothing better than a friend, unless it is a friend with chocolate.", author = "Linda Grayson" },
    { text = "Friendship is unnecessary, like philosophy, like art. It has no survival value; rather it is one of those things which give value to survival.", author = "C.S. Lewis" },
    { text = "'You have been my friend,' replied Charlotte. 'That in itself is a tremendous thing.'", author = "E.B. White" },
    { text = "The capacity for friendship is God's way of apologizing for our families.", author = "Jay McInerney" },
    -- happiness
    { text = "Love is that condition in which the happiness of another person is essential to your own.", author = "Robert A. Heinlein" },
    { text = "If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.", author = "J.R.R. Tolkien" },
    { text = "They say a person needs just three things to be truly happy in this world: someone to love, something to do, and something to hope for.", author = "Tom Bodett" },
    { text = "The most important thing is to enjoy your life—to be happy—it's all that matters.", author = "Audrey Hepburn" },
    { text = "You will never be happy if you continue to search for what happiness consists of.", author = "Albert Camus" },
    { text = "Happiness is having a large, loving, caring, close-knit family in another city.", author = "George Burns" },
    -- writing
    { text = "If you don't have time to read, you don't have the time (or the tools) to write.", author = "Stephen King" },
    { text = "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.", author = "Virginia Woolf" },
    { text = "Substitute 'damn' every time you're inclined to write 'very;' your editor will delete it and the writing will be just as it should be.", author = "Mark Twain" },
    { text = "You must stay drunk on writing so reality cannot destroy you.", author = "Ray Bradbury" },
    { text = "Don't tell me the moon is shining; show me the glint of light on broken glass.", author = "Anton Chekhov" },
    { text = "No tears in the writer, no tears in the reader. No surprise in the writer, no surprise in the reader.", author = "Robert Frost" },
    { text = "You never have to change anything you got up in the middle of the night to write.", author = "Saul Bellow" },
    { text = "A classic is a book that has never finished saying what it has to say.", author = "Italo Calvino" },
    { text = "She read books as one would breathe air, to fill up and live.", author = "Annie Dillard" },
    { text = "Words are, of course, the most powerful drug used by mankind.", author = "Rudyard Kipling" },
    { text = "That's what careless words do. They make people love you a little less.", author = "Arundhati Roy" },
    -- knowledge
    { text = "Any fool can know. The point is to understand.", author = "Albert Einstein" },
    { text = "I did then what I knew how to do. Now that I know better, I do better.", author = "Maya Angelou" },
    { text = "No thief, however skillful, can rob one of knowledge, and that is why knowledge is the best and safest treasure to acquire.", author = "L. Frank Baum" },
    { text = "Confidence is ignorance. If you're feeling cocky, it's because there's something you don't know.", author = "Eoin Colfer" },
    { text = "Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in.", author = "Alan Alda" },
    { text = "Wisdom cannot be imparted. Knowledge can be communicated, but not wisdom.", author = "Hermann Hesse" },
    { text = "The mind is not a vessel to be filled, but a fire to be kindled.", author = "Plutarch" },
    -- nature
    { text = "The clearest way into the Universe is through a forest wilderness.", author = "John Muir" },
    { text = "I felt my lungs inflate with the onrush of scenery—air, mountains, trees, people. I thought, 'This is what it is to be happy.'", author = "Sylvia Plath" },
    { text = "Adopt the pace of nature: her secret is patience.", author = "Ralph Waldo Emerson" },
    { text = "I like it when a flower or a little tuft of grass grows through a crack in the concrete. It's so damn heroic.", author = "George Carlin" },
    { text = "In the spring, at the end of the day, you should smell like dirt.", author = "Margaret Atwood" },
    -- courage
    { text = "Can a man still be brave if he's afraid? That is the only time a man can be brave.", author = "George R.R. Martin" },
    { text = "Don't be afraid of your fears. They're not there to scare you. They're there to let you know that something is worth it.", author = "C. JoyBell C." },
    { text = "Life shrinks or expands in proportion to one's courage.", author = "Anaïs Nin" },
    { text = "A ship is safe in harbor, but that's not what ships are for.", author = "John A. Shedd" },
    -- time
    { text = "How did it get so late so soon?", author = "Dr. Seuss" },
    { text = "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.", author = "Mother Teresa" },
    { text = "You can have it all. Just not all at once.", author = "Oprah Winfrey" },
    { text = "Don't spend time beating on a wall, hoping to transform it into a door.", author = "Coco Chanel" },
    { text = "Books have a unique way of stopping time in a particular moment and saying: Let's not forget this.", author = "Dave Eggers" },
    { text = "Time is the longest distance between two places.", author = "Tennessee Williams" },
    -- success
    { text = "Failure gives success its flavor.", author = "Truman Capote" },
    { text = "The greatest glory in living lies not in never falling, but in rising every time we fall.", author = "Oliver Goldsmith" },
    { text = "Don't aim at success. It will come as the unintended side effect of your dedication to a cause greater than yourself.", author = "Viktor E. Frankl" },
    { text = "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", author = "George Bernard Shaw" },
    -- art
    { text = "I dream my painting and I paint my dream.", author = "Vincent van Gogh" },
    { text = "One ought, every day at least, to hear a little song, read a good poem, see a fine picture, and, if it were possible, to speak a few reasonable words.", author = "Johann Wolfgang von Goethe" },
    { text = "If you ask me what I came to do in this world, I, an artist, will answer you: I am here to live out loud.", author = "Émile Zola" },
    { text = "Art and love are the same thing: It's the process of seeing yourself in things that are not you.", author = "Chuck Klosterman" },
    { text = "A great fire burns within me, but no one stops to warm themselves at it, and passers-by only see a wisp of smoke.", author = "Vincent van Gogh" },
    -- death
    { text = "To the well-organized mind, death is but the next great adventure.", author = "J.K. Rowling" },
    { text = "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.", author = "Mark Twain" },
    { text = "Death ends a life, not a relationship.", author = "Mitch Albom" },
    { text = "I seek the Great Perhaps.", author = "François Rabelais" },
    { text = "Unbeing dead isn't being alive.", author = "E.E. Cummings" },
    -- imagination
    { text = "Anyone who lives within their means suffers from a lack of imagination.", author = "Oscar Wilde" },
    { text = "The moment you doubt whether you can fly, you cease for ever to be able to do it.", author = "J.M. Barrie" },
    { text = "Vision is the art of seeing things invisible.", author = "Jonathan Swift" },
    { text = "Imagination is everything. It is the preview of life's coming attractions.", author = "Albert Einstein" },
    { text = "We are what we pretend to be, so we must be careful about what we pretend to be.", author = "Kurt Vonnegut Jr." },
    -- hope
    { text = "You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us.", author = "John Lennon" },
    { text = "I think we dream so we don't have to be apart for so long.", author = "A.A. Milne" },
    { text = "Hope is a waking dream.", author = "Aristotle" },
    { text = "Blessed is he who expects nothing, for he shall never be disappointed.", author = "Alexander Pope" },
    { text = "I like the night. Without the dark, we'd never see the stars.", author = "Stephenie Meyer" },
    -- freedom
    { text = "They who can give up essential liberty to obtain a little temporary safety deserve neither liberty nor safety.", author = "Benjamin Franklin" },
    { text = "Freeing yourself was one thing, claiming ownership of that freed self was another.", author = "Toni Morrison" },
    { text = "You wanna fly, you got to give up the shit that weighs you down.", author = "Toni Morrison" },
    { text = "Freedom is not worth having if it does not include the freedom to make mistakes.", author = "Mahatma Gandhi" },
    -- change
    { text = "Things change. And friends leave. Life doesn't stop for anybody.", author = "Stephen Chbosky" },
    { text = "Everyone thinks of changing the world, but no one thinks of changing himself.", author = "Leo Tolstoy" },
    { text = "Grief does not change you. It reveals you.", author = "John Green" },
    { text = "Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow.", author = "Lao Tzu" },
    { text = "Why do you go away? So that you can come back. So that you can see the place you came from with new eyes and extra colors.", author = "Terry Pratchett" },
    -- poetry
    { text = "I carry your heart with me (I carry it in my heart).", author = "E.E. Cummings" },
    { text = "We love the things we love for what they are.", author = "Robert Frost" },
    { text = "To be nobody but yourself in a world which is doing its best to make you everybody else is to fight the hardest battle any human being can fight.", author = "E.E. Cummings" },
    { text = "Some say the world will end in fire, some say in ice.", author = "Robert Frost" },
    { text = "Music expresses that which cannot be put into words and that which cannot remain silent.", author = "Victor Hugo" },
    -- kindness
    { text = "Indifference and neglect often do much more damage than outright dislike.", author = "J.K. Rowling" },
    { text = "No one has ever become poor by giving.", author = "Anne Frank" },
    { text = "Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.", author = "Desmond Tutu" },
    -- music
    { text = "One good thing about music, when it hits you, you feel no pain.", author = "Bob Marley" },
    { text = "And those who were seen dancing were thought to be insane by those who could not hear the music.", author = "Friedrich Nietzsche" },
    { text = "Music was my refuge. I could crawl into the space between the notes and curl my back to loneliness.", author = "Maya Angelou" },
    { text = "After silence, that which comes nearest to expressing the inexpressible is music.", author = "Aldous Huxley" },
    { text = "We should consider every day lost on which we have not danced at least once.", author = "Friedrich Nietzsche" },
    { text = "Some people have lives; some people have music.", author = "John Green" },
    -- science
    { text = "Never memorize something that you can look up.", author = "Albert Einstein" },
    { text = "Somewhere, something incredible is waiting to be known.", author = "Carl Sagan" },
    { text = "If we knew what it was we were doing, it would not be called research, would it?", author = "Albert Einstein" },
    { text = "An expert is a person who has made all the mistakes that can be made in a very narrow field.", author = "Niels Bohr" },
    { text = "I'm sure the universe is full of intelligent life. It's just been too intelligent to come here.", author = "Arthur C. Clarke" },
    { text = "That which can be asserted without evidence, can be dismissed without evidence.", author = "Christopher Hitchens" },
    { text = "Nothing in life is to be feared, it is only to be understood.", author = "Marie Curie" },
    { text = "Everything must be made as simple as possible. But not simpler.", author = "Albert Einstein" },
    { text = "What an astonishing thing a book is. Writing is perhaps the greatest of human inventions.", author = "Carl Sagan" },
    -- dreams
    { text = "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. Explore. Dream. Discover.", author = "H. Jackson Brown Jr." },
    { text = "I dream. Sometimes I think that's the only right thing to do.", author = "Haruki Murakami" },
    { text = "We are the music makers, and we are the dreamers of dreams.", author = "Arthur O'Shaughnessy" },
    -- books
    { text = "A room without books is like a body without a soul.", author = "Marcus Tullius Cicero" },
    { text = "I have always imagined that Paradise will be a kind of library.", author = "Jorge Luis Borges" },
    { text = "You can never get a cup of tea large enough or a book long enough to suit me.", author = "C.S. Lewis" },
    { text = "Never trust anyone who has not brought a book with them.", author = "Lemony Snicket" },
    { text = "If one cannot enjoy reading a book over and over again, there is no use in reading it at all.", author = "Oscar Wilde" },
    { text = "It is what you read when you don't have to that determines what you will be when you can't help it.", author = "Oscar Wilde" },
    { text = "One must always be careful of books, for words have the power to change us.", author = "Cassandra Clare" },
    { text = "Some day you will be old enough to start reading fairy tales again.", author = "C.S. Lewis" },
    { text = "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.", author = "Jane Austen" },
    { text = "Books are the plane, and the train, and the road. They are the destination, and the journey. They are home.", author = "Anna Quindlen" },
    { text = "Books are the mirrors of the soul.", author = "Virginia Woolf" },
    { text = "Every book has a soul. The soul of the person who wrote it and of those who read it and lived and dreamed with it.", author = "Carlos Ruiz Zafón" },
    -- beauty
    { text = "Sometimes people are beautiful. Not in looks. Not in what they say. Just in what they are.", author = "Markus Zusak" },
    { text = "Think of all the beauty still left around you and be happy.", author = "Anne Frank" },
    { text = "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author = "Marcus Aurelius" },
    { text = "Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.", author = "Rabindranath Tagore" },
    { text = "Youth is happy because it has the capacity to see beauty. Anyone who keeps the ability to see beauty never grows old.", author = "Franz Kafka" },
    { text = "There is no exquisite beauty without some strangeness in the proportion.", author = "Edgar Allan Poe" },
    { text = "Everything has beauty, but not everyone sees it.", author = "Confucius" },
    { text = "You are imperfect, permanently and inevitably flawed. And you are beautiful.", author = "Amy Bloom" },
    -- education
    { text = "I have never let my schooling interfere with my education.", author = "Mark Twain" },
    { text = "You can never be overdressed or overeducated.", author = "Oscar Wilde" },
    { text = "The world is a book and those who do not travel read only one page.", author = "St. Augustine" },
    { text = "Education is the most powerful weapon which you can use to change the world.", author = "Nelson Mandela" },
    { text = "The mind once enlightened cannot again become dark.", author = "Thomas Paine" },
    { text = "Educating the mind without educating the heart is no education at all.", author = "Aristotle" },
    { text = "Children must be taught how to think, not what to think.", author = "Margaret Mead" },
    { text = "Intelligence plus character—that is the goal of true education.", author = "Martin Luther King Jr." },
    -- adventure
    { text = "To die will be an awfully big adventure.", author = "J.M. Barrie" },
    { text = "I know not all that may be coming, but be it what it will, I'll go to it laughing.", author = "Herman Melville" },
    { text = "No, no! The adventures first, explanations take such a dreadful time.", author = "Lewis Carroll" },
    { text = "An adventure is only an inconvenience rightly considered.", author = "G.K. Chesterton" },
    { text = "Let us step into the night and pursue that flighty temptress, adventure.", author = "J.K. Rowling" },
    -- peace
    { text = "An eye for an eye will only make the whole world blind.", author = "Mahatma Gandhi" },
    { text = "Peace begins with a smile.", author = "Mother Teresa" },
    { text = "You cannot find peace by avoiding life.", author = "Michael Cunningham" },
    { text = "Nobody can hurt me without my permission.", author = "Mahatma Gandhi" },
    { text = "When the power of love overcomes the love of power, the world will know peace.", author = "Jimi Hendrix" },
    { text = "Peace cannot be kept by force; it can only be achieved by understanding.", author = "Albert Einstein" },
    { text = "Peace comes from within. Do not seek it without.", author = "Gautama Buddha" },
    -- passion
    { text = "The saddest people I've ever met in life are the ones who don't care deeply about anything at all.", author = "Nicholas Sparks" },
    { text = "Be the flame, not the moth.", author = "Giacomo Casanova" },
    -- mind
    { text = "A mind needs books as a sword needs a whetstone, if it is to keep its edge.", author = "George R.R. Martin" },
    { text = "I will not let anyone walk through my mind with their dirty feet.", author = "Mahatma Gandhi" },
    { text = "Biology gives you a brain. Life turns it into a mind.", author = "Jeffrey Eugenides" },
    { text = "When the heart speaks, the mind finds it indecent to object.", author = "Milan Kundera" },
    { text = "A man's mind is stretched by a new idea or sensation, and never shrinks back to its former dimensions.", author = "Oliver Wendell Holmes Sr." },
    -- soul
    { text = "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.", author = "Friedrich Nietzsche" },
    { text = "Don't gain the world and lose your soul; wisdom is better than silver or gold.", author = "Bob Marley" },
    { text = "Whatever satisfies the soul is truth.", author = "Walt Whitman" },
    -- people
    { text = "Never love anyone who treats you like you're ordinary.", author = "Oscar Wilde" },
    { text = "When someone shows you who they are, believe them the first time.", author = "Maya Angelou" },
    { text = "I do not want people to be very agreeable, as it saves me the trouble of liking them a great deal.", author = "Jane Austen" },
    { text = "Maybe everybody in the whole damn world is scared of each other.", author = "John Steinbeck" },
    { text = "There's just one kind of folks. Folks.", author = "Harper Lee" },
    { text = "The world is dangerous not because of those who do harm, but because of those who look at it without doing anything.", author = "Albert Einstein" },
    { text = "I think there's just one kind of folks. Folks.", author = "Harper Lee" },
    -- age
    { text = "Wrinkles should merely indicate where the smiles have been.", author = "Mark Twain" },
    { text = "Older men declare war. But it is youth that must fight and die.", author = "Herbert Hoover" },
    -- travel
    { text = "The journey of a thousand miles begins with a single step.", author = "Lao Tzu" },
    { text = "A good traveler has no fixed plans and is not intent on arriving.", author = "Lao Tzu" },
    { text = "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", author = "Marcel Proust" },
    { text = "Travel is fatal to prejudice, bigotry, and narrow-mindedness.", author = "Mark Twain" },
    { text = "Travel far enough, you meet yourself.", author = "David Mitchell" },
    { text = "It is good to have an end to journey toward; but it is the journey that matters, in the end.", author = "Ursula K. Le Guin" },
    { text = "Wherever you go becomes a part of you somehow.", author = "Anita Desai" },
    { text = "The traveler sees what he sees. The tourist sees what he has come to see.", author = "G.K. Chesterton" },
    -- war
    { text = "The supreme art of war is to subdue the enemy without fighting.", author = "Sun Tzu" },
    { text = "Appear weak when you are strong, and strong when you are weak.", author = "Sun Tzu" },
    { text = "Never think that war, no matter how necessary, nor how justified, is not a crime.", author = "Ernest Hemingway" },
    { text = "War doesn't determine who's right. War determines who remains.", author = "R.F. Kuang" },
    { text = "Imagination is the only weapon in the war against reality.", author = "Lewis Carroll" },
    { text = "It is forbidden to kill; therefore all murderers are punished unless they kill in large numbers and to the sound of trumpets.", author = "Voltaire" },
    -- loneliness
    { text = "All great and precious things are lonely.", author = "John Steinbeck" },
    { text = "The worst part of holding the memories is not the pain. It's the loneliness of it. Memories need to be shared.", author = "Lois Lowry" },
    { text = "When the snows fall and the white winds blow, the lone wolf dies but the pack survives.", author = "George R.R. Martin" },
    { text = "Two possibilities exist: either we are alone in the Universe or we are not. Both are equally terrifying.", author = "Arthur C. Clarke" },
    { text = "Where you used to be, there is a hole in the world, which I find myself constantly walking around in the daytime, and falling in at night.", author = "Edna St. Vincent Millay" },
    -- magic
    { text = "And above all, watch with glittering eyes the whole world around you because the greatest secrets are always hidden in the most unlikely places.", author = "Roald Dahl" },
    { text = "The world is full of magic things, patiently waiting for our senses to grow sharper.", author = "W.B. Yeats" },
    { text = "Any sufficiently advanced technology is indistinguishable from magic.", author = "Arthur C. Clarke" },
    { text = "We do not need magic to transform our world. We carry all of the power we need inside ourselves already.", author = "J.K. Rowling" },
    { text = "The magic is only in what books say, how they stitched the patches of the universe together into one garment for us.", author = "Ray Bradbury" },
    -- family
    { text = "All happy families are alike; each unhappy family is unhappy in its own way.", author = "Leo Tolstoy" },
    { text = "Show me a family of readers, and I will show you the people who move the world.", author = "Napoleon Bonaparte" },
    { text = "After a good dinner one can forgive anybody, even one's own relations.", author = "Oscar Wilde" },
    -- power
    { text = "If you want to find out what a man is to the bottom, give him power.", author = "Robert G. Ingersoll" },
    { text = "Power is not a means; it is an end.", author = "George Orwell" },
    { text = "The thing women have yet to learn is nobody gives you power. You just take it.", author = "Roseanne Barr" },
    { text = "Once you give a charlatan power over you, you almost never get it back.", author = "Carl Sagan" },
    { text = "I wonder if fears ever really go away, or if they just lose their power over us.", author = "Veronica Roth" },
    { text = "Any human power can be resisted and changed by human beings.", author = "Ursula K. Le Guin" },
    -- patience
    { text = "Rivers know this: there is no hurry. We shall get there some day.", author = "A.A. Milne" },
    { text = "Trees that are slow to grow bear the best fruit.", author = "Molière" },
    { text = "Patience is bitter, but its fruit is sweet.", author = "Aristotle" },
    { text = "He that can have patience can have what he will.", author = "Benjamin Franklin" },
    { text = "The strongest warriors are these two: Time and Patience.", author = "Leo Tolstoy" },
    -- anger
    { text = "Never go to bed mad. Stay up and fight.", author = "Phyllis Diller" },
    { text = "Angry people are not always wise.", author = "Jane Austen" },
    { text = "Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.", author = "Mark Twain" },
    { text = "Bitterness is like cancer. It eats upon the host.", author = "Maya Angelou" },
    { text = "Letting go gives us freedom, and freedom is the only condition for happiness.", author = "Thich Nhat Hanh" },
    -- memory
    { text = "Right now I'm having amnesia and déjà vu at the same time. I think I've forgotten this before.", author = "Steven Wright" },
    { text = "Our memory is a more perfect world than the universe: it gives back life to those who no longer exist.", author = "Guy de Maupassant" },
    { text = "Scars have the strange power to remind us that our past is real.", author = "Cormac McCarthy" },
    { text = "We are all the pieces of what we remember. We hold in ourselves the hopes and fears of those who love us.", author = "Cassandra Clare" },
    { text = "To live in hearts we leave behind is not to die.", author = "Thomas Campbell" },
    { text = "I think it is all a matter of love; the more you love a memory the stronger and stranger it becomes.", author = "Vladimir Nabokov" },
    { text = "A clear conscience is the sure sign of a bad memory.", author = "Mark Twain" },
    { text = "The advantage of a bad memory is that one enjoys several times the same good things for the first time.", author = "Friedrich Nietzsche" },
    -- silence
    { text = "Your silence will not protect you.", author = "Audre Lorde" },
    { text = "Never miss a good chance to shut up.", author = "Will Rogers" },
    { text = "Silence is the real crime against humanity.", author = "Nadezhda Mandelstam" },
    { text = "You can listen to silence and learn from it. It has quality and dimension all its own.", author = "Chaim Potok" },
    { text = "Silence is so freaking loud.", author = "Sarah Dessen" },
    { text = "When truth is replaced by silence, the silence is a lie.", author = "Yevgeny Yevtushenko" },
    { text = "He who doesn't understand your silence won't understand your words.", author = "Elbert Hubbard" },
    { text = "Silence is a source of great strength.", author = "Lao Tzu" },
    -- justice
    { text = "There may be times when we are powerless to prevent injustice, but there must never be a time when we fail to protest.", author = "Elie Wiesel" },
    { text = "Truth never damages a cause that is just.", author = "Mahatma Gandhi" },
    { text = "Justice will not be served until those who are unaffected are as outraged as those who are.", author = "Benjamin Franklin" },
    { text = "The arc of the moral universe is long, but it bends towards justice.", author = "Theodore Parker" },
    { text = "Never forget that justice is what love looks like in public.", author = "Cornel West" },
    { text = "Each of us is more than the worst thing we've ever done.", author = "Bryan Stevenson" },
    { text = "It is better to risk saving a guilty person than to condemn an innocent one.", author = "Voltaire" },
    -- loss
    { text = "It's only after we've lost everything that we're free to do anything.", author = "Chuck Palahniuk" },
    { text = "Don't grieve. Anything you lose comes round in another form.", author = "Rumi" },
    { text = "It's so much darker when a light goes out than it would have been if it had never shone.", author = "John Steinbeck" },
    { text = "Death ends a life, not a relationship.", author = "Mitch Albom" },
    { text = "Love is how you stay alive, even after you are gone.", author = "Mitch Albom" },
    { text = "The meaning of life is that it stops.", author = "Franz Kafka" },
    { text = "Sleep, those little slices of death — how I loathe them.", author = "Edgar Allan Poe" },
    { text = "Each night, when I go to sleep, I die. And the next morning, when I wake up, I am reborn.", author = "Mahatma Gandhi" },
    { text = "Death is so terribly final, while life is full of possibilities.", author = "George R.R. Martin" },
    -- suffering
    { text = "The only way out of the labyrinth of suffering is to forgive.", author = "John Green" },
    { text = "The wound is the place where the Light enters you.", author = "Rumi" },
    { text = "What is hell? I maintain that it is the suffering of being unable to love.", author = "Fyodor Dostoevsky" },
    { text = "Tell your heart that the fear of suffering is worse than the suffering itself.", author = "Paulo Coelho" },
    { text = "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.", author = "Kahlil Gibran" },
    { text = "Do you not see how necessary a world of pains and troubles is to school an intelligence and make it a soul?", author = "John Keats" },
    { text = "Pain and suffering are always inevitable for a large intelligence and a deep heart.", author = "Fyodor Dostoevsky" },
    { text = "Should you shield the canyons from the windstorms you would never see the true beauty of their carvings.", author = "Elisabeth Kübler-Ross" },
    -- identity
    { text = "Never forget what you are, for surely the world will not. Make it your strength. Then it can never be your weakness.", author = "George R.R. Martin" },
    { text = "Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation.", author = "Oscar Wilde" },
    { text = "Nothing of me is original. I am the combined effort of everyone I've ever known.", author = "Chuck Palahniuk" },
    { text = "Perhaps it's impossible to wear an identity without becoming what you pretend to be.", author = "Orson Scott Card" },
    { text = "When I discover who I am, I'll be free.", author = "Ralph Ellison" },
    { text = "Never be bullied into silence. Accept no one's definition of your life, but define yourself.", author = "Harvey Fierstein" },
    { text = "The best way to find yourself is to lose yourself in the service of others.", author = "Mahatma Gandhi" },
    { text = "Human beings are not born once and for all on their birthday. Life obliges them to give birth to themselves over and over.", author = "Gabriel García Márquez" },
    { text = "I am not an angel and I will not be one till I die: I will be myself.", author = "Charlotte Brontë" },
    { text = "Don't let the noise of others' opinions drown out your own inner voice.", author = "Steve Jobs" },
    -- light
    { text = "There is a crack in everything. That's how the light gets in.", author = "Leonard Cohen" },
    { text = "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author = "Plato" },
    { text = "May it be a light to you in dark places, when all other lights go out.", author = "J.R.R. Tolkien" },
    { text = "Only when we are brave enough to explore the darkness will we discover the infinite power of our light.", author = "Brené Brown" },
    { text = "How far that little candle throws his beams! So shines a good deed in a weary world.", author = "William Shakespeare" },
    { text = "One does not become enlightened by imagining figures of light, but by making the darkness conscious.", author = "C.G. Jung" },
    { text = "I will love the light for it shows me the way, yet I will endure the darkness for it shows me the stars.", author = "Og Mandino" },
    -- god
    { text = "If we find ourselves with a desire that nothing in this world can satisfy, the most probable explanation is that we were made for another world.", author = "C.S. Lewis" },
    { text = "All God does is watch us and kill us when we get boring. We must never, ever be boring.", author = "Chuck Palahniuk" },
    { text = "God has no religion.", author = "Mahatma Gandhi" },
    { text = "Prayer changes the one who prays, not God.", author = "Søren Kierkegaard" },
    { text = "Never fear trusting an unknown future to a known God.", author = "Corrie ten Boom" },
    { text = "Dogs think you're god. Cats conclude they are gods.", author = "Christopher Hitchens" },
    { text = "Some men are so worried about the next world they never learn to live in this one.", author = "Harper Lee" },
    -- more life
    { text = "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", author = "H. Jackson Brown Jr." },
    { text = "Hard times create strong men. Strong men create good times. Good times create weak men. Weak men create hard times.", author = "G. Michael Hopf" },
    { text = "One day I will find the right words, and they will be simple.", author = "Jack Kerouac" },
    { text = "To say goodbye is to die a little.", author = "Raymond Chandler" },
    { text = "At the temple there is a poem called 'Loss' carved into the stone. It has three words, but the poet has scratched them out. You cannot read loss, only feel it.", author = "Arthur Golden" },
    { text = "One lives in the hope of becoming a memory.", author = "Antonio Porchia" },
    { text = "The Greek word for 'return' is nostos. Algos means 'suffering.' So nostalgia is the suffering caused by an unappeased yearning to return.", author = "Milan Kundera" },
    -- more humor
    { text = "Everything in the world is about sex except sex. Sex is about power.", author = "Oscar Wilde" },
    { text = "A book lying idle on a shelf is wasted ammunition.", author = "Henry Miller" },
    { text = "God is silent. Now if only man would shut up.", author = "Woody Allen" },
    { text = "I think God, in creating man, somewhat overestimated his ability.", author = "Oscar Wilde" },
    { text = "Poets have been mysteriously silent on the subject of cheese.", author = "G.K. Chesterton" },
    -- more philosophy
    { text = "You are not your job, your money, your car, or your possessions.", author = "Chuck Palahniuk" },
    { text = "Everyone tells a story about themselves inside their own head. That story makes you what you are.", author = "Patrick Rothfuss" },
    { text = "We can spend our lives letting the world tell us who we are, or we can decide for ourselves.", author = "Chuck Palahniuk" },
    { text = "Biology gives you a brain. Life turns it into a mind.", author = "Jeffrey Eugenides" },
    { text = "The snake which cannot cast its skin has to die. As well the minds which are prevented from changing their opinions; they cease to be mind.", author = "Friedrich Nietzsche" },
    { text = "I am large, I contain multitudes.", author = "Walt Whitman" },
    -- more writing
    { text = "The difference between the almost right word and the right word is the difference between the lightning bug and the lightning.", author = "Mark Twain" },
    { text = "And by the way, everything in life is writable about if you have the outgoing guts to do it, and the imagination to improvise.", author = "Sylvia Plath" },
    { text = "I can never read all the books I want; I can never be all the people I want and live all the lives I want.", author = "Sylvia Plath" },
    { text = "What really knocks me out is a book that, when you're all done reading it, you wish the author was a terrific friend of yours and you could call him up on the phone whenever you felt like it.", author = "J.D. Salinger" },
    -- more books
    { text = "I have always imagined that Paradise will be a kind of library.", author = "Jorge Luis Borges" },
    { text = "What an astonishing thing a book is. Writing is perhaps the greatest of human inventions, binding together people who never knew each other.", author = "Carl Sagan" },
    { text = "Books are the plane, and the train, and the road. They are the destination, and the journey. They are home.", author = "Anna Quindlen" },
    -- more nature
    { text = "Adopt the pace of nature: her secret is patience.", author = "Ralph Waldo Emerson" },
    { text = "There is a pleasure in the pathless woods, there is a rapture on the lonely shore.", author = "Lord Byron" },
    -- more travel
    { text = "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", author = "Marcel Proust" },
    { text = "I travel not to go anywhere, but to go. I travel for travel's sake.", author = "Robert Louis Stevenson" },
    { text = "We travel, some of us forever, to seek other states, other lives, other souls.", author = "Anaïs Nin" },
    -- more science
    { text = "I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.", author = "Albert Einstein" },
    { text = "In the beginning there was nothing, which exploded.", author = "Terry Pratchett" },
    -- more courage
    { text = "I wanted you to see what real courage is — it's when you know you're licked before you begin, but you begin anyway and see it through no matter what.", author = "Harper Lee" },
    { text = "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.", author = "Maya Angelou" },
    -- more wisdom
    { text = "A man's mind is stretched by a new idea or sensation, and never shrinks back to its former dimensions.", author = "Oliver Wendell Holmes Sr." },
    { text = "Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in.", author = "Alan Alda" },
    -- more death
    { text = "Death is so terribly final, while life is full of possibilities.", author = "George R.R. Martin" },
    { text = "Don't think of it as dying. Just think of it as leaving early to avoid the rush.", author = "Terry Pratchett" },
    -- more loneliness
    { text = "The trouble is not that I am single and likely to stay single, but that I am lonely and likely to stay lonely.", author = "Charlotte Brontë" },
    { text = "Remember: the time you feel lonely is the time you most need to be by yourself. Life's cruelest irony.", author = "Douglas Coupland" },
    -- more magic
    { text = "The world is full of magic things, patiently waiting for our senses to grow sharper.", author = "W.B. Yeats" },
    { text = "Believe something and the Universe is on its way to being changed. Because you've changed, by believing.", author = "Diane Duane" },
    -- more music
    { text = "If music be the food of love, play on.", author = "William Shakespeare" },
    { text = "After silence, that which comes nearest to expressing the inexpressible is music.", author = "Aldous Huxley" },
    -- more imagination
    { text = "Stories of imagination tend to upset those without one.", author = "Terry Pratchett" },
    { text = "Our imagination flies — we are its shadow on the earth.", author = "Vladimir Nabokov" },
    -- more people
    { text = "I do not want people to be very agreeable, as it saves me the trouble of liking them a great deal.", author = "Jane Austen" },
    { text = "All great and precious things are lonely.", author = "John Steinbeck" },
    -- more war
    { text = "All war is a symptom of man's failure as a thinking animal.", author = "John Steinbeck" },
    { text = "There is no flag large enough to cover the shame of killing innocent people.", author = "Howard Zinn" },
    -- more hope
    { text = "But I know, somehow, that only when it is dark enough can you see the stars.", author = "Martin Luther King Jr." },
    -- more beauty
    { text = "The most beautiful people we have known are those who have known defeat, known suffering, known struggle, known loss, and have found their way out of the depths.", author = "Elisabeth Kübler-Ross" },
    -- more freedom
    { text = "Anxiety is the dizziness of freedom.", author = "Søren Kierkegaard" },
    -- more education
    { text = "The mind once enlightened cannot again become dark.", author = "Thomas Paine" },
    { text = "Educating the mind without educating the heart is no education at all.", author = "Aristotle" },
    -- more friendship
    { text = "You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.", author = "A.A. Milne" },
    -- more happiness
    { text = "Insanity is doing the same thing, over and over again, but expecting different results.", author = "Narcotics Anonymous" },
    -- more art
    { text = "One ought, every day at least, to hear a little song, read a good poem, see a fine picture, and, if it were possible, to speak a few reasonable words.", author = "Johann Wolfgang von Goethe" },
    -- food
    { text = "One cannot think well, love well, sleep well, if one has not dined well.", author = "Virginia Woolf" },
    { text = "There is no love sincerer than the love of food.", author = "George Bernard Shaw" },
    { text = "There are people in the world so hungry, that God cannot appear to them except in the form of bread.", author = "Mahatma Gandhi" },
    { text = "Seize the moment. Remember all those women on the Titanic who waved off the dessert cart.", author = "Erma Bombeck" },
    { text = "I cook with wine, sometimes I even add it to the food.", author = "W.C. Fields" },
    -- creativity
    { text = "We have to continually be jumping off cliffs and developing our wings on the way down.", author = "Kurt Vonnegut Jr." },
    { text = "Learn the rules like a pro, so you can break them like an artist.", author = "Pablo Picasso" },
    { text = "The worst enemy to creativity is self-doubt.", author = "Sylvia Plath" },
    { text = "Nothing is original. Steal from anywhere that resonates with inspiration or fuels your imagination.", author = "Jim Jarmusch" },
    { text = "To be creative means to be in love with life.", author = "Osho" },
    { text = "An idea that is not dangerous is unworthy of being called an idea at all.", author = "Oscar Wilde" },
    { text = "Great minds discuss ideas. Average minds discuss events. Small minds discuss people.", author = "Henry Thomas Buckle" },
    -- gratitude
    { text = "Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.", author = "Marcel Proust" },
    { text = "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for.", author = "Epicurus" },
    { text = "We can complain because rose bushes have thorns, or rejoice because thorns have roses.", author = "Alphonse Karr" },
    { text = "Walk as if you are kissing the Earth with your feet.", author = "Thich Nhat Hanh" },
    { text = "Piglet noticed that even though he had a Very Small Heart, it could hold a rather large amount of Gratitude.", author = "A.A. Milne" },
    -- simplicity
    { text = "If you can't explain it to a six year old, you don't understand it yourself.", author = "Albert Einstein" },
    { text = "Life is really simple, but we insist on making it complicated.", author = "Confucius" },
    { text = "Our life is frittered away by detail. Simplify, simplify.", author = "Henry David Thoreau" },
    { text = "There is no greatness where there is not simplicity, goodness, and truth.", author = "Leo Tolstoy" },
    { text = "It is not a daily increase, but a daily decrease. Hack away at the inessentials.", author = "Bruce Lee" },
    { text = "One should use common words to say uncommon things.", author = "Arthur Schopenhauer" },
    -- wonder
    { text = "Write it on your heart that every day is the best day in the year.", author = "Ralph Waldo Emerson" },
    { text = "Wonder is the beginning of wisdom.", author = "Socrates" },
    { text = "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author = "Albert Einstein" },
    { text = "You'll never find a rainbow if you're looking down.", author = "Charlie Chaplin" },
    { text = "The more clearly we can focus our attention on the wonders and realities of the universe about us, the less taste we shall have for destruction.", author = "Rachel Carson" },
    { text = "The pursuit of truth and beauty is a sphere of activity in which we are permitted to remain children all our lives.", author = "Albert Einstein" },
    -- regret
    { text = "The only thing people regret is that they didn't live boldly enough, that they didn't invest enough heart, didn't love enough.", author = "Ted Hughes" },
    { text = "Marry, and you will regret it; don't marry, and you will also regret it. Marry or don't marry, you will regret it either way.", author = "Søren Kierkegaard" },
    { text = "One of the greatest regrets in life is being what others would want you to be, rather than being yourself.", author = "Shannon L. Alder" },
    { text = "Of all the words of mice and men, the saddest are, 'It might have been.'", author = "Kurt Vonnegut Jr." },
    -- curiosity
    { text = "The best thing for being sad is to learn something. That's the only thing that never fails.", author = "T.H. White" },
    { text = "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.", author = "Richard P. Feynman" },
    { text = "Why is it that when one man builds a wall, the next man immediately needs to know what's on the other side?", author = "George R.R. Martin" },
    { text = "Curiosity is, in great and generous minds, the first passion and the last.", author = "Samuel Johnson" },
    { text = "The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires.", author = "William Arthur Ward" },
    { text = "Curiosity killed the cat. People always forget: 'And satisfaction brought it back.'", author = "Tamora Pierce" },
    -- morning
    { text = "Morning is wonderful. Its only drawback is that it comes at such an inconvenient time of day.", author = "Glen Cook" },
    { text = "Be willing to be a beginner every single morning.", author = "Meister Eckhart" },
    { text = "I love the smell of book ink in the morning.", author = "Umberto Eco" },
    { text = "The longest way must have its close — the gloomiest night will wear on to a morning.", author = "Harriet Beecher Stowe" },
    -- more misc high-likes
    { text = "Never love anyone who treats you like you're ordinary.", author = "Oscar Wilde" },
    { text = "It is better to be hated for what you are than to be loved for what you are not.", author = "André Gide" },
    { text = "There is neither happiness nor misery in the world; there is only the comparison of one state with another.", author = "Alexandre Dumas" },
    { text = "I've never been lonely. I've been in a room — I've felt suicidal. I've been depressed. I've felt awful — but I never felt that one other person could enter that room and cure what was bothering me.", author = "Charles Bukowski" },
    { text = "When you compare the sorrows of real life to the pleasures of the imaginary one, you will never want to live again, only to dream forever.", author = "Alexandre Dumas" },
    { text = "As my sufferings mounted I soon realized that there were two ways in which I could respond — either to react with bitterness or seek to transform the suffering into a creative force.", author = "Martin Luther King Jr." },
    { text = "If you have a sister and she dies, do you stop saying you have one? Or are you always a sister, even when the other half of the equation is gone?", author = "Jodi Picoult" },
    { text = "I am a citizen of the world.", author = "Diogenes" },
    { text = "Wherever you go, there you are.", author = "Confucius" },
    { text = "We must be willing to let go of the life we planned so as to have the life that is waiting for us.", author = "Joseph Campbell" },
    { text = "There is a place in the heart that will never be filled; a space. And even during the best moments, we will know it.", author = "Charles Bukowski" },
    { text = "I have learned that if you must leave a place you have lived in and loved, leave it any way except a slow way.", author = "Beryl Markham" },
    { text = "Now more than ever do I realize that I will never be content with a sedentary life.", author = "Isabelle Eberhardt" },
    { text = "You only live twice: once when you are born, and once when you look death in the face.", author = "Ian Fleming" },
    { text = "If I'm sincere today, what does it matter if I regret it tomorrow?", author = "José Saramago" },
    { text = "Blessed is the man who, having nothing to say, abstains from giving wordy evidence of the fact.", author = "George Eliot" },
    { text = "When I pronounce the word Silence, I destroy it.", author = "Wisława Szymborska" },
    { text = "What I like about photographs is that they capture a moment that's gone forever, impossible to reproduce.", author = "Karl Lagerfeld" },
    -- solitude
    { text = "I respect myself and my existence the more when alone, friendless, and unsustained.", author = "Charlotte Brontë" },
    { text = "My imagination functions much better when I don't have to speak to people.", author = "Patricia Highsmith" },
    { text = "The greatest skill is to belong to yourself.", author = "Michel de Montaigne" },
    { text = "Freedom exists only in solitude.", author = "Arthur Schopenhauer" },
    { text = "Solitude is more companionable than company.", author = "Henry David Thoreau" },
    -- universe
    { text = "A book, too, can be a star, a living fire to lighten the darkness, leading out into the expanding universe.", author = "Madeleine L'Engle" },
    { text = "I bet you could sometimes find all the mysteries of the universe in someone's hand.", author = "Benjamin Alire Sáenz" },
    { text = "Nothing happens until something moves.", author = "Albert Einstein" },
    { text = "The universe is a pretty big place. If it's just us, seems like an awful waste of space.", author = "Carl Sagan" },
    { text = "Through our eyes, the universe is perceiving itself. Through our ears, the universe is listening to its harmonies.", author = "Alan W. Watts" },
    { text = "We are an impossibility in an impossible universe.", author = "Ray Bradbury" },
    -- misc
    { text = "It is better to risk saving a guilty person than to condemn an innocent one.", author = "Voltaire" },
    { text = "I've got a bad case of the 3:00 am guilts — when you lie in bed and replay all those things you didn't do right.", author = "D.D. Barant" },
    { text = "Compassion hurts. When you feel connected to everything, you also feel responsible for everything.", author = "Andrew Boyd" },
    { text = "Sometimes life knocks you on your ass. Get up, get up, get up. Happiness is not the absence of problems; it's the ability to deal with them.", author = "Steve Maraboli" },
    { text = "Closed in a room, my imagination becomes the universe, and the rest of the world is missing out.", author = "Criss Jami" },
    { text = "I see it all perfectly; one can either do this or that. Do it or do not do it — you will regret both.", author = "Søren Kierkegaard" },
    { text = "Time was passing like a hand waving from a train I wanted to be on.", author = "Jonathan Safran Foer" },
    { text = "It's so curious: one can resist tears and behave well in grief. But then someone makes a friendly sign and everything collapses.", author = "Colette" },
    { text = "We are going to die, and that makes us the lucky ones.", author = "Richard Dawkins" },
    { text = "The public have an insatiable curiosity to know everything, except what is worth knowing.", author = "Oscar Wilde" },
    { text = "The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires.", author = "William Arthur Ward" },
    { text = "Despite your best efforts, people are going to be hurt when it's time for them to be hurt.", author = "Haruki Murakami" },
    { text = "We are all the pieces of what we remember.", author = "Cassandra Clare" },
    { text = "There is a place in the heart that will never be filled; a space. And even during the best moments, we will know it.", author = "Charles Bukowski" },
    { text = "The soul is placed in the body like a rough diamond, and must be polished, or the luster of it will never appear.", author = "Daniel Defoe" },
    { text = "Grief does not change you. It reveals you.", author = "John Green" },
    { text = "Scars have the strange power to remind us that our past is real.", author = "Cormac McCarthy" },
    { text = "Well-organized mind sees death as the next great adventure.", author = "J.K. Rowling" },
    { text = "Books become friends; where all your yesteryears are buried deep.", author = "Joshua Slocum" },
    { text = "Never doubt that a small group of thoughtful, committed citizens can change the world. Indeed, it is the only thing that ever has.", author = "Margaret Mead" },
    { text = "Some men are so worried about the next world they never learn to live in this one.", author = "Harper Lee" },
    { text = "The soul fortunately has an interpreter — often an unconscious but still a faithful interpreter — in the eye.", author = "Charlotte Brontë" },
    { text = "How did it get so late so soon?", author = "Dr. Seuss" },
    { text = "I believe in the power of the imagination to remake the world, to release the truth within us.", author = "J.G. Ballard" },
    { text = "Wherever you go, there you are.", author = "Confucius" },
    { text = "We must never, ever be boring.", author = "Chuck Palahniuk" },
    { text = "There is no such thing as a moral or an immoral book. Books are well written, or badly written. That is all.", author = "Oscar Wilde" },
    { text = "Pull up a chair. Take a taste. Come join us. Life is so endlessly delicious.", author = "Ruth Reichl" },
    -- work
    { text = "Be nice to nerds. You may end up working for them.", author = "Charles J. Sykes" },
    { text = "I like work: it fascinates me. I can sit and look at it for hours.", author = "Jerome K. Jerome" },
    { text = "Be steady and well-ordered in your life so you can be fierce and original in your work.", author = "Gustave Flaubert" },
    { text = "All happiness depends on courage and work.", author = "Honoré de Balzac" },
    { text = "Without ambition one starts nothing. Without work one finishes nothing.", author = "Ralph Waldo Emerson" },
    { text = "We miss opportunity because it's dressed in overalls and looks like work.", author = "Thomas Edison" },
    { text = "Action may not bring happiness, but there is no happiness without action.", author = "William James" },
    { text = "I like what is in work — the chance to find yourself, your own reality.", author = "Joseph Conrad" },
    { text = "Your career will never wake up and tell you it doesn't love you anymore.", author = "Lady Gaga" },
    { text = "Out of clutter, find simplicity.", author = "Albert Einstein" },
    { text = "Find your purpose and give your whole heart and soul to it.", author = "Gautama Buddha" },
    { text = "Be completely engaged with what you're doing. Call it play, not work.", author = "Alan Watts" },
    { text = "I don't dream at night, I dream all day; I dream for a living.", author = "Steven Spielberg" },
    { text = "The only way to do great work is to love what you do.", author = "Steve Jobs" },
    { text = "Genius is one percent inspiration and ninety-nine percent perspiration.", author = "Thomas Edison" },
    { text = "Choose a job you love, and you will never have to work a day in your life.", author = "Confucius" },
    { text = "You miss one hundred percent of the shots you don't take.", author = "Wayne Gretzky" },
    { text = "Whether you think you can, or you think you can't — you're right.", author = "Henry Ford" },
    { text = "If you're going through hell, keep going.", author = "Winston Churchill" },
    { text = "The secret of getting ahead is getting started.", author = "Mark Twain" },
}
